insert into restaurant (id, name, city, state, zip_code, version) values(1, 'Subway', 'Plymouth', 'WI', '53073', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(2, 'Boston Market', 'Gaithersburg', 'MD', '20877', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(3, 'Subway Subs', 'Santa Teresa', 'NM', '88008', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(4, 'Arby''s Roast Beef Restaurant', 'Klamath Falls', 'OR', '97603', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(5, 'Bellefleur Winery & Restaurant', 'Carlsbad', 'CA', '92008', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(6, 'Huddle House', 'Calhoun', 'GA', '30701', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(7, 'John Browne''s Pub & Eatery', 'Indianapolis', 'IN', '46235', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(8, 'Ling''s Express', 'Milwaukee', 'WI', '53217', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(9, 'Chubys''s', 'Odell', 'OR', '97044', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(10, 'Bojangles', 'Columbia', 'SC', '29203', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(11, 'NPC International', 'Memphis', 'TN', '38134', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(12, 'Pancake Cafe', 'Naperville', 'IL', '60540', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(13, 'Hong & Kong Restaurant', 'Chelmsford', 'MA', '01824', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(14, 'The Chicken Cooperative', 'Ketchum', 'OK', '74349', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(15, 'Subway', 'Lonoke', 'AR', '72086', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(16, 'Domino''s Pizza', 'Loveland', 'CO', '80537', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(17, 'Carl''s Jr', 'Peoria', 'IL', '61615', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(18, 'El Toro Bar & Grill', 'Shawnee', 'KS', '66216', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(19, 'Subway Sandwiches & Salads', 'New Orleans', 'LA', '70123', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(20, 'Subway', 'Decatur', 'GA', '30030', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(21, 'Arby''s', 'Indianapolis', 'IN', '46268', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(22, 'China King', 'Cedar Rapids', 'IA', '52404', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(23, 'Subway Sandwiches & Salads', 'Knoxville', 'TN', '37924', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(24, 'Luciano Italian Restaurant', 'Oakton', 'VA', '22124', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(25, 'Fruition', 'Portland', 'OR', '97210', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(26, 'Blough''s Delicatessen', 'Davidsville', 'PA', '15928', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(27, 'Hardee''s of Murfreesboro No 4', 'Murfreesboro', 'TN', '37128', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(28, 'Dairy Queen restaurant ', 'Carter Lake', 'IA', '51510', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(29, 'Imperial Wok Chinese Restaurant', 'Shreveport', 'LA', '71118', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(30, 'Hardee''s', 'Waldorf', 'MD', '20601', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(31, 'Cinnabon', 'Gainesville', 'FL', '32605', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(32, 'Angle Inn Restaurant', 'Rockford', 'IL', '61103', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(33, 'Casey''s Carry Out Pizza', 'Thomson', 'IL', '61285', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(34, 'Sonic Drive In', 'Salt Lake City', 'UT', '84118', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(35, 'Mcdonald''s restaurant ', 'Racine', 'WI', '53406', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(36, 'Huhot Mongolian Grill', 'Omaha', 'NE', '68154', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(37, 'Giovanni''s Pizzeria', 'Las Vegas', 'NV', '89123', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(38, 'Bangkok Royal', 'Waco', 'TX', '76706', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(39, 'Golden Coin Bake Shop & Restaurant', 'Waipahu', 'HI', '96797', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(40, 'Cristaudo''s Grand Avenue', 'Carbondale', 'IL', '62901', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(41, 'O''Charley''s Restaurant', 'Independence', 'MO', '64057', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(42, 'A1 Ocean Cafe', 'San Francisco', 'CA', '94104', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(43, 'Alberto''s Mexican Food', 'Corona', 'CA', '92880', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(44, 'Beach Dog Computer Center', 'Hilo', 'HI', '96720', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(45, 'Burger King', 'Houston', 'TX', '77070', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(46, 'Fox River Brew Pub', 'Oshkosh', 'WI', '54901', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(47, 'Buffas Delicatessen', 'New York', 'NY', '10012', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(48, 'Maria''s Mexican Bistro Inc', 'Brooklyn', 'NY', '11215', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(49, 'Sue''s Restaurant', 'Providence', 'RI', '02903', 1);
insert into restaurant (id, name, city, state, zip_code, version) values(50, 'Dairy Queen Brazier', 'Cameron', 'MO', '64429', 1);
